apiVersion: v1
kind: ConfigMap
metadata:
  name: rest-service-config
  labels:
    app.kubernetes.io/name: rest-service
    app.kubernetes.io/part-of: data-connect-hub
data:
  config.toml: |
    [server]
    address = "0.0.0.0"
    port = 8080

    [global-connection-types]
    tenant-id = "opendatahub"

    [flight-service]
    address = "flight-service"
    port = 8443
    sa_token_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"

    [flight-service.tls]
    ca_cert_file = "/etc/service-ca/service-ca.crt"
