apiVersion: v1
kind: ConfigMap
metadata:
  name: rest-service-kube-rbac-proxy-config
  labels:
    app.kubernetes.io/name: rest-service
    app.kubernetes.io/part-of: data-connect-hub
data:
  config-file.yaml: |
    authorization:
      endpoints:
        - path: /api/v1/data/connections/*/readiness
          mappings:
            - methods: [post]
              resources:
                - rewrites:
                    byHttpHeader:
                      name: X-Tenant-Id
                  resourceAttributes:
                    namespace: "{{.FromHeader}}"
                    apiGroup: dataconnecthub.opendatahub.io
                    resource: data-connections
                    verb: create
        - path: /api/v1/data/connections/*
          mappings:
            - methods: [get, post, patch, delete]
              resources:
                - rewrites:
                    byHttpHeader:
                      name: X-Tenant-Id
                  resourceAttributes:
                    namespace: "{{.FromHeader}}"
                    apiGroup: dataconnecthub.opendatahub.io
                    resource: data-connections
                    verb: "{{.FromMethod}}"
        - path: /api/v1/data/connections
          mappings:
            - methods: [get, post]
              resources:
                - rewrites:
                    byHttpHeader:
                      name: X-Tenant-Id
                  resourceAttributes:
                    namespace: "{{.FromHeader}}"
                    apiGroup: dataconnecthub.opendatahub.io
                    resource: data-connections
                    verb: "{{.FromMethod}}"
        - path: /api/v1/data/connection-types/*
          mappings:
            - methods: [get, post, patch, delete]
              resources:
                - rewrites:
                    byHttpHeader:
                      name: X-Tenant-Id
                  resourceAttributes:
                    namespace: "{{.FromHeader}}"
                    apiGroup: dataconnecthub.opendatahub.io
                    resource: data-connection-types
                    verb: "{{.FromMethod}}"
        - path: /api/v1/data/connection-types
          mappings:
            - methods: [get, post]
              resources:
                - rewrites:
                    byHttpHeader:
                      name: X-Tenant-Id
                  resourceAttributes:
                    namespace: "{{.FromHeader}}"
                    apiGroup: dataconnecthub.opendatahub.io
                    resource: data-connection-types
                    verb: "{{.FromMethod}}"
        - path: /api/v1/data/test/credentials
          mappings:
            - methods: [post]
              resources:
                - rewrites:
                    byHttpHeader:
                      name: X-Tenant-Id
                  resourceAttributes:
                    namespace: "{{.FromHeader}}"
                    apiGroup: dataconnecthub.opendatahub.io
                    resource: data-connections
                    verb: create
