apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: data-connect-hub
  labels:
    app.kubernetes.io/part-of: data-connect-hub
spec:
  parentRefs:
    - name: odh-gateway
      namespace: opendatahub
  rules:
    - matches:
        - path:
            type: Exact
            value: /api/v1/data/health
        - path:
            type: PathPrefix
            value: /api/v1/data/connections
        - path:
            type: PathPrefix
            value: /api/v1/data/connection-types
        - path:
            type: PathPrefix
            value: /api/v1/data/test
      backendRefs:
        - name: rest-service
          port: 8443
    - matches:
        - path:
            type: PathPrefix
            value: /grpc.health.v1.Health
        - path:
            type: PathPrefix
            value: /arrow.flight.protocol.FlightService
      backendRefs:
        - name: flight-service
          port: 8443
