apiVersion: v1
kind: Service
metadata:
  name: flight-service
  labels:
    app.kubernetes.io/name: flight-service
    app.kubernetes.io/part-of: data-connect-hub
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: flight-service-tls
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: flight-service
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
