[package]
name = "flight-service"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[lib]
name = "flight_service"
path = "src/lib.rs"

[[bin]]
name = "flight-service"
path = "src/main.rs"

[dependencies]
postgres-connector = { workspace = true }
sqlite-connector = { workspace = true }
s3-connector = { workspace = true }
milvus-connector = { workspace = true }
elasticsearch-connector = { workspace = true }
neo4j-connector = { workspace = true }
uri-connector = { workspace = true }
async-trait = { workspace = true }
commons = { workspace = true }
pg-meta-store = { workspace = true }
arrow = { workspace = true }
arrow-flight = { workspace = true, features = ["flight-sql"] }
tonic = { workspace = true, features = ["tls-aws-lc"] }
tonic-health = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "fs", "signal"] }
futures = { workspace = true }
prost = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
bytes = { workspace = true }
tokio-stream = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
config = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
kube-utils = { workspace = true }
tower = { workspace = true }
rustls = { version = "0.23", default-features = false, features = ["aws_lc_rs"] }
http = { workspace = true }
http-body = { workspace = true }
http-body-util = { workspace = true }
actix-web = { workspace = true }
metrics = "0.24.6"
metrics-exporter-prometheus = { version = "0.18.3", default-features = false }

[dev-dependencies]
sqlx = { workspace = true }
opendal = { workspace = true }
parquet = { workspace = true }
arrow-csv = { workspace = true }
